### ISSUE TITLE
Deployment to AWS Lambda with Zappa fails

### ISSUE THREAD

**Issue by joerg86** [johnwheeler/flask-ask#148] opened 2017-06-25 13:11 UTC
Trying the example in this blog post:
https://developer.amazon.com/de/blogs/post/8e8ad73a-99e9-4c0f-a7b3-60f92287b0bf/new-alexa-tutorial-deploy-flask-ask-skills-to-aws-lambda-with-zappa

Deployment works without any problems, but when calling the app, I get this JSON back:

`{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\n', ' File "/var/task/handler.py", line 433, in handler\n response = Response.from_app(self.wsgi_app, environ)\n', ' File "/tmp/pip-build-ePaynQ/Werkzeug/werkzeug/wrappers.py", line 903, in from_app\n', ' File "/tmp/pip-build-ePaynQ/Werkzeug/werkzeug/test.py", line 884, in run_wsgi_app\n', "TypeError: 'NoneType' object is not callable\n"]}`

It seems that this line in repo_stats.py causes the import error:
`from flask_ask import Ask, statement`

If I remove the flask_ask imports, it works fine. No problem to deploy a "normal" flask app with Zappa using the way described in the tutorial.

requirements.txt:

```
aniso8601==1.2.0
argcomplete==1.8.2
asn1crypto==0.22.0
awscli==1.11.112
base58==0.2.4
boto3==1.4.4
botocore==1.5.75
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
colorama==0.3.7
cryptography==1.9
docutils==0.13.1
durationpy==0.4
enum34==1.1.6
Flask==0.12.1
Flask-Ask==0.9.4
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
kph==0.3
lambda-packages==0.15.1
MarkupSafe==1.0
pkg-resources==0.0.0
placebo==0.8.1
pyasn1==0.2.3
pycparser==2.17
pyOpenSSL==17.0.0
python-dateutil==2.6.0
python-slugify==1.2.4
python-telegram-bot==6.1.0
PyYAML==3.12
requests==2.18.1
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.2

```

Thx,
Jörg

**Comment by joerg86** [comment] 2017-06-25 14:19
Finally, I found the problem (see traceback at the end):
The cyptography module (installed via lambda_packages) contains an import from packaging.version. Add this to requirements.txt and it works!

`packaging==16.8`

```
Traceback (most recent call last):
File "/var/task/handler.py", line 490, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 240, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 129, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/var/task/repo_stats.py", line 18, in <module>
from flask_ask import Ask, statement
File "/tmp/pip-build-ePaynQ/Flask-Ask/flask_ask/__init__.py", line 9, in <module>
File "/tmp/pip-build-ePaynQ/Flask-Ask/flask_ask/core.py", line 12, in <module>
File "/tmp/pip-build-ePaynQ/Flask-Ask/flask_ask/verifier.py", line 8, in <module>
File "/tmp/pip-build-ePaynQ/pyOpenSSL/OpenSSL/__init__.py", line 8, in <module>
File "/tmp/pip-build-ePaynQ/pyOpenSSL/OpenSSL/crypto.py", line 13, in <module>
File "/tmp/tmpIWCFLD/lib64/python/cryptography/hazmat/primitives/asymmetric/dsa.py", line 11, in <module>
File "/tmp/tmpIWCFLD/lib64/python/cryptography/utils.py", line 13, in <module>
ImportError: No module named packaging.version
```

**Comment by shaansheikh** [comment] 2017-06-30 18:31
@joerg86 I'm having the same error. How do you add this to requirements.txt? I tried running "pip freeze > requirements.txt" and putting the file in the root folder of the app and adding "packaging==16.8" to it.  I'm still getting the error. Do you have to do anything to get zappa to use the requirements.txt file?

**Comment by mc51** [comment] 2017-06-30 22:58
@shaansheikh: just doing "pip install packaging.version" should resolve the error. Thereafter, re-deploy with zappa. The module will be included on your Lambda environment. For me, this worked.

**Comment by remimarenco** [comment] 2017-07-04 02:29
I have the same issue, and it seems to be related to the compilation on Mac:

`/var/task/cryptography/hazmat/bindings/_openssl.abi3.so: invalid ELF header: ImportError
Traceback (most recent call last):
File "/var/task/handler.py", line 490, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 240, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 129, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/var/task/cds_alexa.py", line 7, in <module>
from flask_ask import Ask, statement, question, session
File "/var/task/flask_ask/__init__.py", line 9, in <module>
from .core import (
File "/var/task/flask_ask/core.py", line 12, in <module>
from . import verifier, logger
File "/var/task/flask_ask/verifier.py", line 8, in <module>
from OpenSSL import crypto
File "/var/task/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "/var/task/OpenSSL/rand.py", line 12, in <module>
from OpenSSL._util import (
File "/var/task/OpenSSL/_util.py", line 6, in <module>
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/var/task/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /var/task/cryptography/hazmat/bindings/_openssl.abi3.so: invalid ELF header`

**Comment by m19brandon** [comment] 2017-07-10 00:47
* Not run "pip install packaging.version", this does not exist
* Run this "pip install packaging"

* Then "zappa update env" to redeploy

Notice this in the output when building the package. Not sure if this is the cause.

> Downloading and installing dependencies..
>  cryptography==1.9: Warning! Using precompiled lambda package version 1.8.1 instead!

**Closed** 2017-07-31 05:02 UTC
