### ISSUE TITLE
Audio not working anymore

### ISSUE THREAD

**Issue by silverWeaver** [johnwheeler/flask-ask#110] opened 2017-03-20 08:56 UTC
I think return audio(speech).play(stream_url) isn't working anymore.
Alexa replies "Something went wrong with the response".

I tried to execute the exact example demo inside folder "audio".

**Comment by johnwheeler** [comment] 2017-03-21 02:19
Can anyone else confirm with an existing skill? I can't reproduce this.

**Comment by Christina96** [comment] 2017-03-22 21:33
I tried three examples. Both from the [audio folder](https://github.com/johnwheeler/flask-ask/tree/master/samples/audio) and one of my own. All three played.

**Comment by johnwheeler** [comment] 2017-03-22 22:33
Thank you @Christina96 - closing this issue until more info is provided or someone can reproduce and include debug info / stacktraces

**Closed by johnwheeler** 2017-03-22 22:33 UTC

**Comment by nkaviani** [comment] 2017-03-28 05:50
I had a similar issue, and in my case it was due to the following error 

```The requested skill has not declared that it implements the AudioPlayer interface. Please update the skill's configuration from the Developer Console.```

The library only returns a `400` error and fails silently. It is probably a good idea to let errors like these bubble up.

**Comment by Christina96** [comment] 2017-03-28 07:27
When you fill the Skill information (Alexa Skill Kit), did you check the field for Audio Player?
![default](https://cloud.githubusercontent.com/assets/15112370/24393435/c02e4304-13a0-11e7-9198-f9aa20f14f1b.png)

**Comment by nkaviani** [comment] 2017-03-28 07:39
yes. I fixed the problem before writing the comment. thanks. My comment was mostly about making the errors more visible to the user.

**Comment by shaolinkhoa** [comment] 2017-04-24 08:01
hi @Christina96 ,
I already checked the field for Audio Player
But when I tried 2 projects from the [audio sample folder](https://github.com/johnwheeler/flask-ask/tree/master/samples/audio)
Alexa didn't play any sound from url. Alexa just return the statement then I didn't hear any song.
I copied those mp3 url and open them in my browser, those mp3 url are still alive.

**Comment by skgali** [comment] 2017-04-29 22:31
I tried to run the Audio samples... but couldn't... the https respose is INTERNAL SERVER ERROR and here is the stack trace

Traceback (most recent call last):
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\core.py", line 594, in _flask_view_func
    result = self._map_intent_to_view_func(self.request.intent)()
  File "C:\apps\PycharmProjects\TestProj\Alexa\ask_audio.py", line 26, in demo
    return audio(speech).play(stream_url, offset=93000)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\models.py", line 154, in play
    directive['audioItem'] = self._audio_item(stream_url=stream_url, offset=offset)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\models.py", line 208, in _audio_item
    push_stream(stream_cache, context['System']['user']['userId'], stream)
  File "C:\apps\Python\Python36-32\lib\site-packages\werkzeug\local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
TypeError: 'NoneType' object is not subscriptable

**Comment by skgali** [comment] 2017-04-29 22:33
seems like the issue is with this statement:
return audio(speech).play(stream_url, offset=93000)

**Comment by voutilad** [comment] 2017-04-30 13:58
@skgali how are you sending requests to the application? Chance are you're not forming a valid `context` object with a userId in your request. 

Make sure you're structuring requests containing `context` objects per [Amazon's examples](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-standard-request-types-reference#launchrequest-example).

If you're still experiencing issues after adding contexts, please open a separate issue so we can track this more specifically as an issue related to context processing when handling audio requests.
