### ISSUE TITLE
Alexa session timeout time

### ISSUE THREAD

**Issue by C-Volume** [johnwheeler/flask-ask#93] opened 2017-01-26 00:50 UTC
I have some questions about session timeout 

When i set the service endpoint in the lambda , 8's could happen session timeout

but i set  service endpoint in the https (flask-ask) , 2~4's could happen session timeout 

Is it possible to extend the flask-ask's time (not set reprompt)?

**Comment by johnwheeler** [comment] 2017-01-26 00:53
I think this is a dupe of 

https://github.com/johnwheeler/flask-ask/issues/44

I don't think it is possible to set the timeout from the server. If lambda is allowing a longer timeout than an HTTP endpoint, that would be an issue with the Alexa Service and outside Flask-Ask

**Comment by C-Volume** [comment] 2017-01-26 08:16
Ok.... 
Thank you for your answer & python code

**Closed** 2017-01-26 15:03 UTC
