### ISSUE TITLE
Issuing a statement without returning?

### ISSUE THREAD

**Issue by acritelli** [johnwheeler/flask-ask#68] opened 2016-12-29 23:18 UTC
Hey all,

Is there a way to issue a statement to Alexa without actually returning from the function? I'm trying to use Alexa to kick off something that will take awhile and then just give confirmation to the user that the process has started. I obviously don't want to make the user wait 5+ minutes while this runs. Basically, what I have in mind is:

```
@ask.intent("SomeFunction")
def someFunction():
     statement("I've started doing some function")
     <do stuff here that takes awhile>
     return
```

The only way that I can think of to accomplish this right now would be to spin off a thread, return the statement (which breaks out of the someFunction function), and let the thread do its thing. However, then I'd basically lose all control over the thread and have to hope for the best.

Any thoughts? Thank you!

I'm new to flask-ask, so sorry if this is the wrong place to post. I didn't see a mailing list or anything like that. Awesome job on the library though, it made getting started with Alexa super easy.

**Comment by johnwheeler** [comment] 2016-12-30 00:00
Please try this and let me know if you're able to get it to work.

http://flask.pocoo.org/snippets/53/

John

**Comment by acritelli** [comment] 2016-12-30 00:45
@johnwheeler Thanks, I think this will solve my problem, but I might be implementing it wrong. I'm currently using the code below, and it doesn't seem to send a statement back to Alexa until the test_after_request() function is done being called (at which point Alexa has timed out). Am I misunderstanding the correct usage?

```.py
@ask.intent("SomeFunction")
def someFunction():
     @after_this_request
     def test_after_request(response):
          <do stuff here that takes awhile>
          return response
     return statement("I've started doing some function")
```

**Comment by johnwheeler** [comment] 2016-12-30 02:30
I don't think this will work. The problem is that the callback augments the request, but ultimately the request is returned afterwards with or without it. This might be a limitation/artifact of Flask, WSGI, or HTTP itself, I don't really understand the mechanics of what's going on to talk intelligently.

I'm sorry I can't be of more help. I'll leave the issue open for a few more days to give others a chance to respond, but it looks like some sort of async call is the way to go.

**Comment by foxy82** [comment] 2016-12-30 13:11
I didn't think Alexa is allowed to just "speak" without being asked  for
something. I believe it can only speak in response to a request. So whilst
you can do the "started" bit I don't think you can do the finished without
asking Alexa yourself "Alexa has the task finished".

You could possibly fudge the experience by using the audio API and play a
blank 10s mp3 on loop and stop looping once the task has completed at which
point you could return a voice response (see the playlist sample). This
works as a song finishing play triggers a request for Alexa on what to do
next. This obviously has the downside that you will be in audio mode and as
such if you do anything else audio you won't get your finished (E.g. asking
to play music after you kick your task off)

(Note: obviously it is possible to make Alexa just speak - E.G. Amazon do
this for the timer. I don't believe this is exposed to other developers
over the API).

**Comment by acritelli** [comment] 2016-12-30 13:43
@foxy82 She would be asked something. The scenario I had in mind would be:

1. Utterance: Alexa, do this thing
2. Alexa: OK, I've started doing that thing. It should be done in 5 or 10 minutes.

That would be the end of the interaction, and a process would work in the background (I think I'm just going to accomplish this using a thread).

At any rate: I agree, it would be cool if Amazon exposed the ability to just speak (like with the timer) to developers. That would be pretty cool for my use case also. Good thought!

**Comment by relighted** [comment] 2017-01-01 14:43
Afaik the notification feature is being developed,  would be cool in any case. 
For your skill,  why not store state in a db? Use the user ID and register the processing status.

**Closed** 2017-01-07 01:37 UTC
